#!/bin/bash

file="$1"
local="$2"

if [ "$local" = "--debug" ]
then
  echo "=========DEBUG=========="
  command=""
else
  command="docker run --read-only -v `pwd`:/code -w /code -i runner timeout 1 "
fi

extension="${file##*.}"

case "$extension" in
  "js")
    lang="node"
    ;;
  "php")
    lang="php"
    ;;
  *)
    echo "Language not supported"
    exit 1
    ;;
esac

$command $lang $file
