#!/bin/bash

file="$1"
local="$2"
filename="${file%%.*}"
extension="${file##*.}"

if [ "$local" = "--debug" ]
then
  echo "=========DEBUG=========="
  command=""
else
  command="docker run --read-only -v `pwd`:/code -w /code -i runner timeout 0.300s "
fi

case "$extension" in
  "js")
    lang="node"
    ;;
  "php")
    lang="php"
    ;;
  "pl")
    lang="perl"
    ;;
  "py")
    lang="python"
    ;;
  "rb")
    lang="ruby"
    ;;
  "java")
    echo "java"
    $command javac "$file" && java "$filename"
    exit;
    ;;
  *)
    echo "Language not supported"
    exit 1
    ;;
esac


$command $lang $file
